### ISSUE TITLE
Move from standalone to Fawe-depend

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/voxel-sniper-flattened#21]
Within the recent removal of the internal async wrapper of Fawe, Favs now fails to work if Fawe is present.
We could let Favs depend on Fawe again, as it always did, and simply let Fawe handle the stuff, as it always did.
The async wrapper I added is only a temporary workaround.

**Comment by TheKalien** [comment]
Has anything been done about this yet? not sure how to see if it's been fixed, I have the latest version of FAWE now and the issue still persists, so I'm assuming not :)

**Comment by NotMyFault** [comment]
As you can see, the workflow is empty.

**Comment by TheKalien** [comment]
Sorry, gonna be honest and say I don't know what that means.
